# Generated by Django 4.1.4 on 2022-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
