# Generated by Django 4.1.4 on 2022-12-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0005_alter_student_debt_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.CharField(blank=True, choices=[('13/06/2565', '13/06/2565'), ('14/06/2565', '14/06/2565'), ('15/06/2565', '15/06/2565'), ('16/06/2565', '16/06/2565'), ('17/06/2565', '17/06/2565')], max_length=255, null=True)),
                ('interview_time', models.CharField(blank=True, choices=[('10.00-11.00 น.', '10.00-11.00 น.'), ('11.00-12.00 น.', '11.00-12.00 น.'), ('13.00-14.00 น.', '13.00-14.00 น.'), ('14.00-15.00 น.', '14.00-15.00 น.')], max_length=255, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('uni_ss_b1', models.FloatField(blank=True, null=True)),
                ('uni_ss_b2', models.FloatField(blank=True, null=True)),
                ('uni_ss_c', models.FloatField(blank=True, null=True)),
                ('fac_ss_b1', models.FloatField(blank=True, null=True)),
                ('fac_ss_b2', models.FloatField(blank=True, null=True)),
                ('fac_ss_c', models.FloatField(blank=True, null=True)),
                ('ext_ss_b1', models.FloatField(blank=True, null=True)),
                ('ext_ss_b2', models.FloatField(blank=True, null=True)),
                ('ext_ss_c', models.FloatField(blank=True, null=True)),
                ('total_ss', models.FloatField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1')], null=True)),
            ],
        ),
    ]
