# Generated by Django 4.1.4 on 2022-12-13 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0006_interview_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='interview_session',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarshipmanager.student'),
        ),
        migrations.AddField(
            model_name='interview_session',
            name='interviewers',
            field=models.ManyToManyField(to='scholarshipmanager.interviewer'),
        ),
    ]
