# Generated by Django 4.1.4 on 2022-12-13 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarshipmanager', '0007_interviewer_interview_session_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
