# Generated by Django 4.1.4 on 2022-12-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0008_interviewer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewer',
            old_name='user',
            new_name='interviewer_id',
        ),
    ]
