# Generated by Django 4.1.4 on 2022-12-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0009_rename_user_interviewer_interviewer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_session',
            name='status',
            field=models.IntegerField(blank=True, choices=[('NotSuccess', 'NotSuccess'), ('Success', 'Success')], null=True),
        ),
    ]
