# Generated by Django 4.1.4 on 2022-12-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0010_alter_interview_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_session',
            name='status',
            field=models.CharField(blank=True, choices=[('NotSuccess', 'NotSuccess'), ('Success', 'Success')], max_length=255, null=True),
        ),
    ]
