# Generated by Django 4.1.4 on 2022-12-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0012_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentFormOfApplication',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentOtherDocument',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentPicture',
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
