# Generated by Django 4.1.4 on 2022-12-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0013_remove_student_studentformofapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
