# Generated by Django 4.1.4 on 2022-12-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0016_alter_student_profile_pic_alter_student_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interviewer',
        ),
    ]
