# Generated by Django 4.1.4 on 2022-12-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0017_delete_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dormitory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_type',
            field=models.CharField(blank=True, choices=[('หอพักนิสิตจุฬาฯ', 'หอพักนิสิตจุฬาฯ'), ('หอพักเอกชน', 'หอพักเอกชน'), ('บ้าน', 'บ้าน')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, choices=[('การบัญชี (Accounting)', 'การบัญชี (Accounting)'), ('บริหาร-การจัดการเพื่อเป็นผู้ประกอบการธุรกิจ (Entrepreneurial Management)', 'บริหาร-การจัดการเพื่อเป็นผู้ประกอบการธุรกิจ (Entrepreneurial Management)'), ('บริหาร-ระบบสารสนเทศทางการจัดการ (Management Information Systems)', 'บริหาร-ระบบสารสนเทศทางการจัดการ (Management Information Systems)'), ('บริหาร-การธนาคารและการเงิน (Banking and Finance)', 'บริหาร-การธนาคารและการเงิน (Banking and Finance)'), ('บริหาร-การตลาด (Marketing)', 'บริหาร-การตลาด (Marketing)'), ('บริหาร-การจัดการโลจิสติกส์ระหว่างประเทศ (International Logistics Management)', 'บริหาร-การจัดการโลจิสติกส์ระหว่างประเทศ (International Logistics Management)'), ('สถิติ-สถิติประยุกต์ (Applied Statistics)', 'สถิติ-สถิติประยุกต์ (Applied Statistics)'), ('สถิติ-เทคโนโลยีสารสนเทศเพื่อธุรกิจ (Information Technology for Business)', 'สถิติ-เทคโนโลยีสารสนเทศเพื่อธุรกิจ (Information Technology for Business)'), ('สถิติ-ประกันภัย (Insurance)', 'สถิติ-ประกันภัย (Insurance)'), ('ป.โท', 'ป.โท')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/target.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status_parent',
            field=models.CharField(blank=True, choices=[('อยู่ด้วยกัน', 'อยู่ด้วยกัน'), ('หย่าร้าง', 'หย่าร้าง'), ('แยกกันอยู่', 'แยกกันอยู่'), ('บิดาถึงแก่กรรม', 'บิดาถึงแก่กรรม'), ('มารดาถึงแก่กรรม', 'มารดาถึงแก่กรรม')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, choices=[('ปี1', 'ปี1'), ('ปี2', 'ปี2'), ('ปี3', 'ปี3'), ('ปี4', 'ปี4'), ('ปี5', 'ปี5')], max_length=255, null=True),
        ),
    ]
