# Generated by Django 4.1.4 on 2022-12-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanager', '0021_remove_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default='images/default_profile_pic.jpg', null=True, upload_to='images/'),
        ),
    ]
